### PR TITLE
Use details.internal_name instead to disambiguate taxon titles

### PR DESCRIPTION
**Pull request by Jideboris**
The PR consists of steps to add a new data (internal_name) field to search.taxon table to be available for UI search.

### CODE REVIEW

**Comment by nacnudus** [comment]
This has been deployed to staging for testing, using local instance of the app running https://github.com/alphagov/govuk-knowledge-graph-search/pull/62.  It works, however it has brought to our attention some unexpected, informal use of the `internal_name` field that might perturb users, so we won't merge or deploy this for now.

**Comment by nacnudus** [comment]
https://trello.com/c/NAH2nNVd/2241-use-the-internal-name-of-taxons
https://github.com/alphagov/govuk-knowledge-graph-gcp/issues/381

**Comment by j-marvin-GDS** [comment]
Sample SQL: 

```
with taxons as (
  SELECT 1 as id, 'Money' as title, 'Money [B]' as internal_name
  UNION ALL
  SELECT 1 as id, 'News and events' as title, 'News and events (The Netherlands)' as internal_name
  UNION ALL
  SELECT 1 as id, 'News and events' as title, "News and events ('merica)" as internal_name
)
SELECT
  title,
  internal_name,
  COUNT(title) OVER (PARTITION BY title) AS n,
  CASE WHEN 
  COUNT(title) OVER (PARTITION BY title) = 1 THEN title
  ELSE internal_name
  END AS name
FROM taxons
```

**Review by nacnudus — COMMENTED** [review]
@j-marvin-GDS and I paired on this.

**Review by j-marvin-GDS — APPROVED** [review]

**Pull request merged**
